from snakemake.utils import min_version


# Configuration
configfile: "config/config.yaml"


# Settings
min_version("7.32.4")


# Modules
module tfbscan:
    snakefile:
        "https://raw.githubusercontent.com/ctubbs750/tfbs-scan/main/workflow/Snakefile"
    config:
        config


module unibind:
    snakefile:
        "https://raw.githubusercontent.com/ctubbs750/unibind/main/workflow/Snakefile"
    config:
        config


module activity:
    snakefile:
        "rules/activity.smk"
    config:
        config["TFBS-ACTIVITY"]


# Import modules
use rule * from tfbscan as tfbscan_*


use rule * from unibind as unibind_*


use rule * from activity as activity_*


###
# Main
###


rule all:
    input:
        rules.unibind_all.input,
        rules.tfbscan_all.input,
        rules.activity_all.input,
