"""Main ruleset for creating allfiles"""


configfile: "config/config.yaml"


# Define modules
module pwmscan:
    snakefile:
        "https://raw.githubusercontent.com/ctubbs750/pwm-scan/main/workflow/Snakefile"
    config:
        config

module unibind:
    snakefile:
        "rules/unibind.smk"
    config:
        config

module activity:
    snakefile:
        "rules/activity.smk"
    config:
        config
    

# Import modules
use rule * from pwmscan as pwmscan_*
use rule * from unibind as unibind_*
use rule * from activity as activity_*

###
# Main
###


rule all:
    input:
        rules.pwmscan_all.input,
        rules.unibind_all.input,
        rules.activity_all.input,
    default_target: True
