from snakemake.utils import min_version

min_version("7.0")


configfile: "config/config.yaml"


# Define modules
module tfbscan:
    snakefile:
        "https://raw.githubusercontent.com/ctubbs750/tfbs-scan/main/workflow/Snakefile"
    config:
        config


module unibind:
    snakefile:
        "rules/unibind.smk"
    config:
        config


module activity:
    snakefile:
        "rules/activity.smk"
    config:
        config


# Import modules
use rule * from tfbscan as tfbscan_*


use rule * from unibind as unibind_*


use rule * from activity as activity_*


###
# Main
###


rule all:
    input:
        rules.activity_all.input,
    default_target: True
