###
# TFBS-ACTIVITY parameters
###

TFBS-ACTIVITY:
  # Insallation and processing directories
  INSTALL_DIR: ../resources/data/unibind
  PROCESS_DIR: ../results/activity
  # URL for UNIBIND data download
  UNIBIND_URL: https://unibind.uio.no/static/data/20220914/bulk_Robust/Homo_sapiens/damo_hg38_all_TFBS.tar.gz

###
# PWM-SCAN parameters
###

PWM-SCAN:
  # PWMScan software
  MATRIX_PROB: resources/software/PWMScan/matrix_prob.c
  MATRIX_SCAN: resources/software/PWMScan/matrix_scan.c
  # Target JASPAR profiles to scan against
  TARGETS:
    - MA0139.1 # CTCf
    - MA0007.3 # FOXA1
    - MA0080.1 # SLP1
  # Insallation and processing directories
  INSTALL_DIR: ../resources
  PROCESS_DIR: ../results/pwmscan

###
# Genome parameters
###

GENOME:
  # Genome build
  ASSEMBLY: hg38
  # Genome host
  PROVIDER: UCSC
  # Regex filtering - filter FASTA to main chromosomes
  FILTER: chr[0-9XY]+$
  # Target installation directory
  OUTDIR: ../resources/data/genome
